---
- hosts: centos
  become: yes
  tasks:
    - name: download remote file
      get_url: 
        url: http://redrockdigimark.com/apachemirror/tomcat/tomcat-7/v7.0.82/bin/apache-tomcat-7.0.82.tar.gz
        dest: /usr/local/
        backup: yes 
    - name: unarchivethe files
      unarchive:
        src: /usr/local/apache-tomcat-7.0.82.tar.gz
        dest: /usr/local/
        owner: tomcat
        remote_src: yes
    - name: rename file and create openmrs directory
      command: mv /usr/local/apache-tomcat-7.0.82 /usr/local/tomcat
      command: mkdir /usr/local/tomcat/webapps 
      command: mkdir /usr/local/tomcat/.OpenMRS 
      command: chown -R tomcat:tomcat /usr/local/tomcat
    - name: download remote file open mrs
      get_url: 
        url: https://excellmedia.dl.sourceforge.net/project/openmrs/releases/OpenMRS_Platform_2.0.5/openmrs.war 
        dest: /usr/local/tomcat/webapps/
        backup: yes 
    - name: execute startup scriprt 
    - script: /usr/local/tomcat/bin/startup.sh











