---
- hosts: centos
  become: yes
  tasks:
    - name: download remote file
      get_url: 
        url: http://redrockdigimark.com/apachemirror/tomcat/tomcat-7/v7.0.82/bin/apache-tomcat-7.0.82.tar.gz
        dest: /usr/local/
        backup: yes 
    - name: unarchivethe files
      unarchive:
        src: /usr/local/apache-tomcat-7.0.82.tar.gz
        dest: /usr/local/
        owner: tomcat
        remote_src: yes
    - name: rename file
      command: mv /usr/local/apache-tomcat-7.0.82 /usr/local/tomcat
      command: chown -R tomcat:tomcat /usr/local/tomcat

          


