# file: mariadb.yml
- hosts: centos
  become: yes
  tasks:
  - name: Install MariaDB Server
    yum: name=mariadb-server state=latest update_cache=yes
  - name: install maridb client
    yum:
      name: mariadb
      state: present
  - name: Create a new database 
      mysql_db:
        name: openmrsdb
        state: present
  - name: create user on mariadb
      mysql_user:
        name: badamtest
        host: localhost
        password: 12345
        priv: '*.*:ALL'
        state: present