---
- hosts: centos
  become: yes
  tasks: 
  - name: Create a new badamp test 
    mysql_db:
      login_password: 12345
      login_user: root   
      name: badam
      state: present
  - name: create user on badam test user
    mysql_user:
      login_password: 12345
      login_user: root   
      name: badamtest
      host: localhost
      password: 12345
      priv: '*.*:ALL'
      state: present